# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwzBxXrt5QPnUiRs6d6wMMJuRYOHOTtX
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
# %matplotlib inline

ls

lassa = pd.read_csv("convertcsv.csv")

lassa.head()

lassa.columns

Bbox = (lassa.Latitude.min(), lassa.Latitude.max(), 
        lassa.Longitude.min(), lassa.Longitude.max())

Bbox

map = plt.imread("2019-11-09_08-38-11.png")


# unhash to activate the codes below

#fig, ax = plt.subplots(figsize=(2,8))      
plt.scatter(lassa.Longitude, lassa.Latitude,  alpha= 0.2, c='b', s=10)
plt.title('Plotting Lassa for West Africa')
#ax.set_xlim(Bbox[0],Bbox[1])
#ax.set_ylim(Bbox[2],Bbox[3])

plt.imshow(map, zorder=0, extent = Bbox, aspect= 'equal')

a = plt.imread("2019-11-09_08-38-11.png")
plt.imshow(a)

